### ISSUE TITLE
Temperature sensor 

### ISSUE THREAD

**Issue by miggi92** [JeffSteinbok/hass-dreo#20]
It would be nice if the temperature isn't a attribute of the fan but an separate entity. 
And the temperature unit is fahrenheit would be nice if the unit is the same as the default unit of the system. 
Would be nice if it can be similar to this example:
![Screenshot_20230714-113240~2.png](https://github.com/JeffSteinbok/hass-dreo/assets/9019692/1d742840-69d9-42e3-b2d0-aa1c2f1451ca)

**Comment by JeffSteinbok** [comment]
I have it on my list to eventually get to.  In the meantime, you can do it yourself with a template sensor:

```
  - platform: template
    sensors:
      main_bedroom_fan_temperature:
        friendly_name: "Main Bedroom Fan Temperature"
        value_template: "{{ state_attr('fan.main_bedroom_fan', 'temperature') }}"
        unit_of_measurement: '°F'
        icon_template: "{{'mdi:thermometer'}}"  
```
