### ISSUE TITLE
DR-HAF004S Common Angle

### ISSUE THREAD

**Issue by coznkaos** [JeffSteinbok/hass-dreo#223]
Greetings!

Thank you so much for this integration - really enjoy having the Dreo products being able to integrate into Home Assistant.  If possible I would like to request for the DR-HAF004S (and possibly others) to be able to see and change the Common Angle in Home Assistant.  In the Dreo app, under 3D Angle Control, you can create a preset called a Common Angle that moves the fan to a saved position that can be named such as Desk or Bed.  Is it possible to add this as an enittiy so that a smart button could control the position?  I'm not sure, but this may be related to issue #184 Calibration Functionalities.  

Thanks!

**Comment by MalteMatthey** [comment]
The calibration function mentioned in #184 serves a different purpose. It allows you to recalibrate the fan if it’s been manually moved and has lost track of its “standard position” (the center point in both directions).

For your goal, you can achieve this through Home Assistant scripts. Simply create a script (e.g., "move_fan_to_common_angle") where you set the desired angles. You can then trigger this script anytime, and the fan will adjust to the specified direction.

Example (adjust as you need):

```
alias: move_fan_to_common_angle
sequence:
  - action: fan.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: fan.ventilator
  - action: switch.turn_off
    target:
      entity_id:
        - switch.ventilator_horizontally_oscillating
        - switch.ventilator_vertically_oscillating
    data: {}
  - action: number.set_value
    target:
      entity_id: number.ventilator_horizontal_angle
    data:
      value: "0"
  - action: number.set_value
    data:
      value: "30"
    target:
      entity_id: number.ventilator_vertical_angle
description: ""
icon: mdi:fan
```

I've implemented a control like this with this method, where various different angles are stored in scripts:

![image](https://github.com/user-attachments/assets/5505a8d5-fd6b-47ac-9657-bb92da81e2d3)
